# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_url', models.CharField(max_length=250)),
            ],
        ),
    ]
